root = "."
tmp_dir = "tmp"

[build]
  cmd = "templ generate && npx @tailwindcss/cli -i ./static/css/input.css -o ./static/css/output.css && CSS_HASH=$(shasum -a 256 ./static/css/output.css | cut -d' ' -f1) && mv ./static/css/output.css \"./static/css/output_${CSS_HASH}.css\" && go build -o ./tmp/main ./cmd/main.go"
  bin = "tmp/main"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "node_modules"]
  include_ext = ["go", "tpl", "tmpl", "html", "templ"]
  exclude_regex = ["_test.go", "_templ.go", "output_.*\\.css", "output\\.css"]

[log]
  time = true

[color]
  main = "magenta"
  watcher = "cyan"
  build = "yellow"
  runner = "green"

[misc]
  clean_on_exit = true
